### ISSUE TITLE
StLambdaQuiet

### ISSUE THREAD

**Issue by yegor256** [yegor256/xsline#40]
Let's create a new class `StLambdaQuiet`, which will be very similar to `StLambda`, but will catch all checked exceptions and convert them into `IllegalStateException`. Don't forget to handle `InterruptedException` [correctly](https://www.yegor256.com/2015/10/20/interrupted-exception.html).

**Comment by yegor256** [comment]
@MikhailLipanin can you help with this please?

**Comment by MikhailLipanin** [comment]
@yegor256, can we use in Xsline Cactoos objects? It will be more convenient to use `BiFunc` instead `BiFunction` for example, because in `BiFunc` there is a functional method throws an `Exception` by default. (Same as with `Function` -> `Func`).

**Comment by MikhailLipanin** [comment]
Point is that in each class in Cactoos library, there is a comment: `There is no thread-safety guarantee.`, so catching an `InterruptedException` can works bad or I am wrong here?

**Comment by yegor256** [comment]
@MikhailLipanin we shouldn't use Cactoos here. It's a good practice to keep such small libraries as Xsline dependency-free.

**Comment by yegor256** [comment]
@rultor release, tag is `0.14.0`
