### ISSUE TITLE
version 0.13.0 gives NoSuchMethodError

### ISSUE THREAD

**Issue by OlesiaSub** [yegor256/xsline#44]
here is the console output
```
java.lang.NoSuchMethodError: 'void com.yegor256.xsline.StAfter.<init>(com.yegor256.xsline.Shift, com.yegor256.xsline.Shift)'

	at org.eolang.parser.ParsingTrain.lambda$new$1(ParsingTrain.java:105)
	at com.yegor256.xsline.Alterator.next(Alterator.java:64)
	at com.yegor256.xsline.Xsline.pass(Xsline.java:71)
	at org.objectionary.ddr.transform.XslTransformer.transformXml(XslTransformer.kt:69)
...
```

you can check the failing mvn configuration [here](https://github.com/objectionary/ddr/pull/79)

**Comment by yegor256** [comment]
@OlesiaSub I think, you have to do `mvn clean` in your project and then compile everything again. Should work.

**Comment by OlesiaSub** [comment]
@yegor256 I did, it didn't help (

**Comment by OlesiaSub** [comment]
@yegor256 the last version I used was 0.12.2 and everything worked fine

**Comment by yegor256** [comment]
@MikhailLipanin please, check this one

**Comment by yegor256** [comment]
@OlesiaSub btw, check this one: https://github.com/objectionary/eo/pull/1302 It seems that 0.13.0 version is compatible with 0.12.0. Maybe the problem is on your side?

**Comment by MikhailLipanin** [comment]
@yegor256 I tried all day yesterday to understand why the constructor for `StAfter -> StLambda` is not recognized in the error, but I could not find it...., Can you please help me?
In Olesia's code, there is using structure, that described at https://news.eolang.org/2022-08-30-parser-external-usage.html:
there is usage of ` new ParsingTrain().empty()`. So first of all, it calls constructor of `ParsingTrain` and then, returns empty train, so the question is: Why we can't just use `new TrDefault<Shift>` and adding Shifts to it, instead calling `ParsingTrain` ?
BUT, by the way, Why this change don't cause the same error in https://github.com/objectionary/eo/commit/4a57f8127e800d0b53c346458d7dac6570c09a61 ?

**Comment by MikhailLipanin** [comment]
@yegor256, @OlesiaSub I don't know kotlin, but may be there is a difference between this code on Java:
```
XML after = new Xsline(
  new TrClasspath<>(
    new ParsingTrain().empty(),
    "/org/eolang/parser/add-refs.xsl",
    "/org/foo/simple.xsl"
  ).back()
).pass(xmir);
```
and this code on Kotlin:
```
val after = Xsline(
  TrClasspath(
      ParsingTrain().empty(),
      "/org/eolang/parser/add-refs.xsl",
      "/org/eolang/parser/expand-aliases.xsl",
      "/org/eolang/parser/resolve-aliases.xsl"
      // "/org/eolang/parser/wrap-method-calls.xsl"
  ).back()
).pass(xmir)
```

**Comment by yegor256** [comment]
@OlesiaSub the problem, I think belongs to the fact that DDR project (@OlesiaSub is working with) is using two versions of Xsline. One is coming from EO (0.12.0), another one is coming from DDR (0.13.0). The confusion is at this level. @OlesiaSub please, wait until we release EO 0.28.8: https://github.com/objectionary/eo/pull/1302#issuecomment-1266805783

**Comment by OlesiaSub** [comment]
@yegor256 thanks, it helped
@MikhailLipanin thanks for your help too
